project:
  type: website
  resources:
    - CNAME  

website:
  site-url: https://www.vadimelenev.com
  title: "Vadim Elenev"
  twitter-card:
    creator: "@VadimElenev"
    description: "Vadim Elenev, Assistant Professor at Johns Hopkins Carey Business School working on macroeconomics and finance."
    image: resources/Headshot.jpg
    card-style: summary
  open-graph: true
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: discussions.qmd
        text: Discussions
      - href: http://www.github.com/elenev
        text: Code
    tools:
      - icon: filetype-pdf
        text: CV [PDF]
        href: resources/cv.pdf
      - icon: github
        text: Github
        href: https://github.com/elenev        
  back-to-top-navigation: true
  google-analytics: UA-97196765-1
  announcement:
     icon: info-circle
     dismissable: true
     content: "**New Working Paper**: [The Austerity Threshold](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5523180)"
  #   content: "**Call for Papers**: [2025 Carey Finance Conference](https://www.brownbag.org/conference/carey-finance-2025#about) | Deadline: May 18 | Oct 16-17 | Baltimore, MD."
     type: primary
     position: below-navbar
  

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



